In [7]:
import pandas as pd

In [9]:
df = pd.read_csv("demo_file/50_student_data.csv")

print(df)

    student_id              name  age  gender         city course  semester  \
0         1001     Aarav Trivedi   21    Male     Vadodara  BSCIT         2
1         1002        Diya Desai   22    Male    Bhavnagar    BSc         6
2         1003        Kabir Jani   17    Male    Bhavnagar    BBA         5
3         1004       Anaya Patel   21    Male    Ahmedabad    BSc         3
4         1005       Vivaan Shah   17    Male     Vadodara    BBA         4
5         1006    Isha Prajapati   21  Female        Anand   BCom         6
6         1007      Reyansh Shah   18  Female     Jamnagar    BSc         3
7         1008      Myra Trivedi   20    Male     Jamnagar    BCA         3
8         1009     Arjun Chauhan   22    Male     Vadodara     BA         1
9         1010       Kiara Patel   21  Female    Ahmedabad  BSCIT         2
10        1011  Aditya Prajapati   20  Female  Gandhinagar    BCA         1
11        1012      Aadhya Mehta   23    Male        Anand     BA         2
12        1013       Krish Patel   19    Male        Anand    BBA         4
13        1014       Saanvi Shah   20    Male        Anand    BCA         2
14        1015        Dhruv Jani   21    Male        Anand    BSc         3
15        1016         Pari Jani   20    Male        Surat     BA         2
16        1017        Rohan Shah   19  Female  Gandhinagar  BSCIT         4
17        1018       Nisha Mehta   19    Male        Anand     BA         5
18        1019          Dev Shah   18    Male    Ahmedabad    BBA         5
19        1020    Mira Prajapati   23  Female       Rajkot    BSc         1
20        1021         Yash Jani   18  Female        Surat  BSCIT         4
21        1022        Jiya Patel   22    Male       Rajkot    BSc         6
22        1023      Meet Chauhan   23  Female  Gandhinagar    BBA         3
23        1024         Riya Shah   18  Female     Vadodara     BA         6
24        1025       Kunal Mehta   17    Male        Surat    BBA         1
25        1026     Pooja Chauhan   21  Female     Jamnagar    BCA         6
26        1027       Harsh Patel   19  Female    Ahmedabad    BBA         1
27        1028     Tanya Chauhan   21    Male        Surat    BCA         4
28        1029     Manav Chauhan   20    Male    Ahmedabad     BA         6
29        1030         Avni Jani   19    Male     Vadodara     BA         2
30        1031         Jay Patel   22  Female        Surat     BA         4
31        1032        Neha Mehta   20  Female     Jamnagar    BBA         2
32        1033          Om Patel   19    Male    Ahmedabad    BSc         4
33        1034   Kavya Prajapati   21    Male        Surat    BCA         6
34        1035       Parth Desai   17    Male       Rajkot     BA         3
35        1036       Jinal Joshi   17  Female        Anand    BCA         1
36        1037        Sahil Jani   21    Male     Vadodara    BCA         6
37        1038      Khushi Desai   20    Male    Bhavnagar   BCom         4
38        1039   Rahul Prajapati   18    Male     Jamnagar    BSc         4
39        1040         Diya Shah   23    Male     Jamnagar    BCA         4
40        1041     Nirav Chauhan   19    Male  Gandhinagar    BCA         6
41        1042      Aarohi Joshi   18  Female        Surat     BA         1
42        1043   Vansh Prajapati   20  Female        Surat   BCom         6
43        1044      Prisha Desai   20  Female  Gandhinagar    BBA         2
44        1045        Tirth Shah   17  Female  Gandhinagar    BSc         2
45        1046      Mahi Chauhan   22  Female  Gandhinagar  BSCIT         2
46        1047    Krupal Chauhan   17  Female  Gandhinagar  BSCIT         1
47        1048        Esha Mehta   23  Female    Bhavnagar    BBA         2
48        1049     Samar Trivedi   21  Female        Surat   BCom         5
49        1050        Tanvi Shah   21    Male     Vadodara    BBA         4

    marks  attendance_percent
0      53                78.1
1      95                61.1
2      79                95.8
3      54                62.5
4      51                73.0
5      37                98.9
6      36                84.2
7      48                68.0
8      52                71.1
9      90                80.3
10     59                92.3
11     62                80.3
12     38                69.9
13     67                80.9
14     62                95.0
15     72                97.1
16     99                96.9
17     65                95.7
18     76                68.1
19     68                77.9
20     88                76.7
21     51                75.7
22     42                72.6
23     80                86.8
24     93                77.1
25     88                68.5
26     99                72.1
27     51                64.9
28     54                91.1
29    100                97.6
30     37                85.7
31     91                74.6
32     58                70.1
33     35                65.5
34     54                78.7
35     57                89.9
36     53                63.8
37     95                95.4
38     50                66.5
39     42                86.7
40     76                68.9
41     96                88.3
42     48                99.8
43     42                76.2
44     66                76.9
45     59                74.3
46     70                63.7
47     40                74.6
48     47                73.5
49     99                78.3

In [13]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
df.to_excel("./demo_file/50_student_data.xlsx", index=False)

In [16]:
df.to_excel("50_student_data.xlsx", index=False)

In [19]:
display(df)

,student_id,name,age,gender,city,course,semester,marks,attendance_percent
0,1001,Aarav Trivedi,21,Male,Vadodara,BSCIT,2,53,78.1
1,1002,Diya Desai,22,Male,Bhavnagar,BSc,6,95,61.1
2,1003,Kabir Jani,17,Male,Bhavnagar,BBA,5,79,95.8
3,1004,Anaya Patel,21,Male,Ahmedabad,BSc,3,54,62.5
4,1005,Vivaan Shah,17,Male,Vadodara,BBA,4,51,73.0
5,1006,Isha Prajapati,21,Female,Anand,BCom,6,37,98.9
6,1007,Reyansh Shah,18,Female,Jamnagar,BSc,3,36,84.2
7,1008,Myra Trivedi,20,Male,Jamnagar,BCA,3,48,68.0
8,1009,Arjun Chauhan,22,Male,Vadodara,BA,1,52,71.1
9,1010,Kiara Patel,21,Female,Ahmedabad,BSCIT,2,90,80.3
10,1011,Aditya Prajapati,20,Female,Gandhinagar,BCA,1,59,92.3
11,1012,Aadhya Mehta,23,Male,Anand,BA,2,62,80.3
12,1013,Krish Patel,19,Male,Anand,BBA,4,38,69.9
13,1014,Saanvi Shah,20,Male,Anand,BCA,2,67,80.9
14,1015,Dhruv Jani,21,Male,Anand,BSc,3,62,95.0
15,1016,Pari Jani,20,Male,Surat,BA,2,72,97.1
16,1017,Rohan Shah,19,Female,Gandhinagar,BSCIT,4,99,96.9
17,1018,Nisha Mehta,19,Male,Anand,BA,5,65,95.7
18,1019,Dev Shah,18,Male,Ahmedabad,BBA,5,76,68.1
19,1020,Mira Prajapati,23,Female,Rajkot,BSc,1,68,77.9
20,1021,Yash Jani,18,Female,Surat,BSCIT,4,88,76.7
21,1022,Jiya Patel,22,Male,Rajkot,BSc,6,51,75.7
22,1023,Meet Chauhan,23,Female,Gandhinagar,BBA,3,42,72.6
23,1024,Riya Shah,18,Female,Vadodara,BA,6,80,86.8
24,1025,Kunal Mehta,17,Male,Surat,BBA,1,93,77.1
25,1026,Pooja Chauhan,21,Female,Jamnagar,BCA,6,88,68.5
26,1027,Harsh Patel,19,Female,Ahmedabad,BBA,1,99,72.1
27,1028,Tanya Chauhan,21,Male,Surat,BCA,4,51,64.9
28,1029,Manav Chauhan,20,Male,Ahmedabad,BA,6,54,91.1
29,1030,Avni Jani,19,Male,Vadodara,BA,2,100,97.6
30,1031,Jay Patel,22,Female,Surat,BA,4,37,85.7
31,1032,Neha Mehta,20,Female,Jamnagar,BBA,2,91,74.6
32,1033,Om Patel,19,Male,Ahmedabad,BSc,4,58,70.1
33,1034,Kavya Prajapati,21,Male,Surat,BCA,6,35,65.5
34,1035,Parth Desai,17,Male,Rajkot,BA,3,54,78.7
35,1036,Jinal Joshi,17,Female,Anand,BCA,1,57,89.9
36,1037,Sahil Jani,21,Male,Vadodara,BCA,6,53,63.8
37,1038,Khushi Desai,20,Male,Bhavnagar,BCom,4,95,95.4
38,1039,Rahul Prajapati,18,Male,Jamnagar,BSc,4,50,66.5
39,1040,Diya Shah,23,Male,Jamnagar,BCA,4,42,86.7
40,1041,Nirav Chauhan,19,Male,Gandhinagar,BCA,6,76,68.9
41,1042,Aarohi Joshi,18,Female,Surat,BA,1,96,88.3
42,1043,Vansh Prajapati,20,Female,Surat,BCom,6,48,99.8
43,1044,Prisha Desai,20,Female,Gandhinagar,BBA,2,42,76.2
44,1045,Tirth Shah,17,Female,Gandhinagar,BSc,2,66,76.9
45,1046,Mahi Chauhan,22,Female,Gandhinagar,BSCIT,2,59,74.3
46,1047,Krupal Chauhan,17,Female,Gandhinagar,BSCIT,1,70,63.7
47,1048,Esha Mehta,23,Female,Bhavnagar,BBA,2,40,74.6
48,1049,Samar Trivedi,21,Female,Surat,BCom,5,47,73.5
49,1050,Tanvi Shah,21,Male,Vadodara,BBA,4,99,78.3

In [20]:
display(df.head(10))

,student_id,name,age,gender,city,course,semester,marks,attendance_percent
0,1001,Aarav Trivedi,21,Male,Vadodara,BSCIT,2,53,78.1
1,1002,Diya Desai,22,Male,Bhavnagar,BSc,6,95,61.1
2,1003,Kabir Jani,17,Male,Bhavnagar,BBA,5,79,95.8
3,1004,Anaya Patel,21,Male,Ahmedabad,BSc,3,54,62.5
4,1005,Vivaan Shah,17,Male,Vadodara,BBA,4,51,73.0
5,1006,Isha Prajapati,21,Female,Anand,BCom,6,37,98.9
6,1007,Reyansh Shah,18,Female,Jamnagar,BSc,3,36,84.2
7,1008,Myra Trivedi,20,Male,Jamnagar,BCA,3,48,68.0
8,1009,Arjun Chauhan,22,Male,Vadodara,BA,1,52,71.1
9,1010,Kiara Patel,21,Female,Ahmedabad,BSCIT,2,90,80.3